# Generated by Django 6.0.2 on 2026-02-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('member_spaces', models.JSONField(default=list)),
                ('is_occupied', models.BooleanField(default=False)),
                ('section', models.CharField(default='G', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group_id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(max_length=50, unique=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('section', models.CharField(default='A', max_length=10)),
                ('reference_image', models.CharField(max_length=255)),
                ('is_occupied', models.BooleanField(default=False)),
                ('vehicle_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_state_change', models.DateTimeField(auto_now=True)),
                ('distance_to_entrance', models.IntegerField(default=0)),
                ('in_group', models.BooleanField(default=False)),
                ('group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['space_id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_spaces', models.IntegerField(default=0)),
                ('free_spaces', models.IntegerField(default=0)),
                ('occupied_spaces', models.IntegerField(default=0)),
                ('vehicle_count', models.IntegerField(default=0)),
                ('occupancy_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Parking Statistics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_path', models.CharField(max_length=500)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('video_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(default='car', max_length=50)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parking_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='parking.parkingspace')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
